<template>
	<section>
		<v-row class='py-2' justify='center'>
			<v-col cols='12' lg='8' class='py-2'>
				<v-icon x-small >{{ mdiCircle }}</v-icon> Ensure you have an authenticator app installed on your cell phone (other authenticator apps are available)
			</v-col>
			<v-col cols='12' lg='8' class='py-2'>
				<v-row align='center' class='' justify='center'>
					<v-col
						v-for='(item, index) of appLinks'
						:key='index'
						cols='auto'
						class=''
					>
						<a
							:href='item.href'
							rel='noopener noreferrer'
							target='_blank'
						>
							<v-btn >
								<v-icon>{{ item.icon }}</v-icon>
								{{ item.platform }}
							</v-btn>
						</a>
					</v-col>
				</v-row>
			</v-col>
		</v-row>
		<v-row class='py-2' justify='center'>
			<v-col cols='12' lg='8' class='py-2'>
				<v-icon x-small >{{ mdiCircle }}</v-icon> Use the authenticator app to scan the following qr code (or manually enter the secret)
			</v-col>
		</v-row>
		<v-row class='py-2' justify='center'>
			<v-col cols='auto' class=' text-center py-2'>
				<app-qr-code :value='qrCode' :size='size' level='H' />
				<v-row class='' justify='center'>
					<v-col cols='auto' class='pa-0 text-caption'>
						secret: {{ secret }}
					</v-col>
				</v-row>
			</v-col>
		</v-row>
		<v-row class='py-2' justify='center'>
			<v-col cols='12' lg='8' class='py-2'>
				<v-icon x-small >{{ mdiCircle }}</v-icon> Enter the six digit code generated by the authenticator app into the box below and verify that the code is correct
			</v-col>
		</v-row>
		<v-row justify='center' class='py-2'>
			<v-col cols='auto' class='py-2'>
				<v-text-field
					v-model='userToken'
					@keydown.enter='verify'
					:autofocus='true'
					:dense='$vuetify.breakpoint.smAndDown'
					:error-messages='errorMessage'
					:prepend-inner-icon='mdiCellphoneInformation'
					class='mb-n6'
					label='app generated code'
					outlined
					required
				/>
			</v-col>
		</v-row>
		<v-row align='center' justify='center' class='py-2'>
			<v-col cols='auto'>
				<v-btn
					@click='cancel'
					color='error'
				>
					<v-icon>{{ mdiClose }}</v-icon>
					cancel
				</v-btn>

			</v-col>
			<v-col cols='auto'>
				<v-btn
					@click='verify'
					color='secondary'
					:disabled='!userToken'
				>
					<v-icon>{{ mdiCheck }}</v-icon>
					verify
				</v-btn>
			</v-col>
		</v-row>
	</section>
</template>

<script lang='ts'>
import { axios_authenticatedUser } from '@/services/axios';
import { mdiApple, mdiClose, mdiCheck, mdiCircle, mdiCellphoneInformation, mdiGooglePlay } from '@mdi/js';
import { snackSuccess } from '@/services/snack';
import { su } from '@/types';
import { twoFAModule, userModule } from '@/store';
import QrcodeVue from 'qrcode.vue';
import Vue from 'vue';

export default Vue.extend({
	name: 'enable-two-fa',

	async beforeDestroy () {
		this.cancel();
	},

	components: {
		appQrCode: QrcodeVue,
	},

	computed: {
		active (): boolean {
			return twoFAModule().alwaysRequired;
		},
		backup (): boolean {
			return twoFAModule().backup;
		},
		secret (): su {
			return twoFAModule().secret;
		},
		email (): su {
			return userModule().email;
		},
		qrCode (): string {
			return `otpauth://totp/mealpedant:${this.email}?secret=${this.secret}&issuer=mealpedant&digits=6&period=30`;
		},
		size (): number {
			return this.$vuetify.breakpoint.mdAndUp ? 200 : 125;
		}
	},

	data: () => ({
		errorMessage: undefined as su,
		mdiCellphoneInformation,
		mdiCheck,
		mdiCircle,
		mdiClose,
		userToken: undefined as su,
		appLinks: [
			{
				href: 'https://apps.apple.com/us/app/microsoft-authenticator/id983156458',
				icon: mdiApple,
				platform: 'iOS'
			},
			{
				href: 'https://play.google.com/store/apps/details?id=com.azure.authenticator&hl=en_US',
				icon: mdiGooglePlay,
				platform: 'android'
			}
		],
	}),

	methods: {
		async cancel (): Promise<void> {
			Promise.all([
				axios_authenticatedUser.setupTwoFA_delete(),
				twoFAModule().set_secret(undefined),
				twoFAModule().set_setupProcessStarted(false),
			]);
		},
		async verify (): Promise<void> {
			if (!this.userToken) {
				this.errorMessage = 'code required';
				return;
			}
			else if (!(/^[0-9]{6}$/).test(this.userToken.replace(/\s/g, ''))) {
				this.errorMessage = 'code invalid';
				return;
			}
			const response = await axios_authenticatedUser.setupTwoFA_post({ token: this.userToken });
			if (response) {
				Promise.all([
					axios_authenticatedUser.setupTwoFA_delete(),
					twoFAModule().set_active(true),
					twoFAModule().set_secret(undefined),
					twoFAModule().set_setupProcessStarted(false),
				]);
				snackSuccess({ message: 'Two Factor Authentication activated' });
			}
		}
	},
	
	watch: {
		userToken (i): void {
			if (!i) this.errorMessage = undefined;
		}
	}
});
</script>
