<template>
	<section>
		<v-row align='center' justify='center' class='ma-0 pa-0'>
			<v-col cols='12' lg='8' class='pl-0 ml-0 text-body-1'>
				Two-Factor Authentication (2FA) is an additional layer of security to protect your Meal Pedant account. When activated,
				you will be required to enter a time sensitive code during login.
				This code can be generated by a cell phone app.
				<br>
				<br>
				Enabling Two-Factor Authentication greatly increases the security and safety of your account, and is highly encouraged.
			</v-col>
		</v-row>
		<v-expand-transition>
			<v-row
				v-if='!setupProcessStarted'
				align='center'
				justify='center'
				class='ma-0 pa-0'
			>
				<v-col cols='auto' class='ml-0 pl-0'>
					<v-btn
						@click='start2FASetup'
						color='secondary'
						variant='flat'
					>
						<v-icon :icon='mdiShieldPlus' />
						enable 2fa
					</v-btn>
				</v-col>
			</v-row>
		</v-expand-transition>
		<v-expand-transition>
			<TFAInstructions v-if='setupProcessStarted' key='a' />
		</v-expand-transition>
	</section>
</template>

<script setup lang='ts'>
import { axios_authenticatedUser } from '@/services/axios';
import { mdiShieldPlus } from '@mdi/js';

const setupProcessStarted = computed((): boolean => {
	return twoFAModule().setupProcessStarted;
});

const start2FASetup = async (): Promise<void> => {
	const secret = await axios_authenticatedUser.setupTwoFA_get();
	if (secret) {
		twoFAModule().set_secret(secret);
		twoFAModule().set_setupProcessStarted(true);
	}
};
</script>