<template>
	<v-row class='ma-0 pa-0' justify='center'>
		<v-col class='ma-0 pa-0' cols='12' lg='8'>
			<v-icon class='mr-1' :icon='mdiCircle' size='x-small' /> Ensure you have an authenticator app installed on your cell
			phone (other authenticator apps are available)
		</v-col>
		<v-col class='ma-0 pa-0' cols='12' lg='8'>
			<v-row align='center' class='' justify='center'>
				<v-col v-for='(item, index) of appLinks' :key='index' class='' cols='auto'>
					<a :href='item.href' rel='noopener noreferrer' target='_blank'>
						<v-btn rounded variant='flat'>
							<v-icon>{{ item.icon }}</v-icon>
							{{ item.platform }}
						</v-btn>
					</a>
				</v-col>
			</v-row>
		</v-col>
	</v-row>
	<v-row class='ma-0 pa-0' justify='center'>
		<v-col class='ma-0 pa-0' cols='12' lg='8'>
			<v-icon class='mr-1' :icon='mdiCircle' size='x-small' />Use the authenticator app to scan the following qr code (or
			manually enter the secret)
		</v-col>
	</v-row>
	<v-row class='ma-0 pa-0 my-2' justify='center'>
		<v-col class='text-center ma-0 pa-0' cols='auto'>
			<QrCode level='H' render-as='svg' :size :value='qrCode' />
			<v-row class='' justify='center'>
				<v-col class='pa-0 text-caption mt-3' cols='auto'>
					secret: {{ secret }}
				</v-col>
			</v-row>
		</v-col>
	</v-row>
	<v-row class='ma-0 pa-0' justify='center'>
		<v-col class='ma-0 pa-0' cols='12' lg='8'>
			<v-icon class='mr-1' :icon='mdiCircle' size='x-small' />
			Enter the six digit code generated by the authenticator app into the box below and verify that the code
			is correct
		</v-col>
	</v-row>
	<v-row class='ma-0 pa-0 my-2' justify='center'>
		<v-col class='ma-0 pa-0' cols='12' lg='2'>
			<v-text-field
				v-model='userToken'
				:autofocus='true'
				class='mb-n6'
				:density='smAndDown ? "compact" : "comfortable"'
				:error-messages='errorMessage'
				label='app generated code'
				:prepend-inner-icon='mdiCellphoneInformation'
				required
				variant='underlined'
				@keydown.enter='verify'
			/>
		</v-col>
	</v-row>
	<v-row align='center' class='ma-0 pa-0' justify='center'>
		<v-col cols='auto'>
			<v-btn color='error' rounded variant='flat' @click='cancel'>
				<v-icon :icon='mdiClose' />
				cancel
			</v-btn>

		</v-col>
		<v-col cols='auto'>
			<v-btn
				:color='!userToken ? "black" : "secondary"'
				:disabled='!userToken'
				rounded
				:variant='!userToken ? "outlined" : "flat"'
				@click='verify'
			>
				<v-icon :icon='mdiCheck' />
				verify
			</v-btn>
		</v-col>
	</v-row>
</template>

<script setup lang='ts'>
import type { PV, su } from '@/types'
import { mdiApple, mdiCellphoneInformation, mdiCheck, mdiCircle, mdiClose, mdiGooglePlay } from '@mdi/js'
import QrCode from 'qrcode.vue'
import { useDisplay } from 'vuetify'
import { axios_authenticatedUser } from '@/services/axios'
import { snackSuccess } from '@/services/snack'
const { smAndDown, mdAndUp } = useDisplay()

onBeforeUnmount(() => {
	cancel()
})

const secret = computed(() => twoFAModule().secret)
const email = computed(() => userModule().email)
const qrCode = computed(() => `otpauth://totp/mealpedant:${email.value}?secret=${secret.value}&issuer=mealpedant&digits=6&period=30`)
const size = computed(() => mdAndUp.value ? 200 : 125)

const errorMessage = ref(undefined as su)
const userToken = ref(undefined as su)
const appLinks = [
	{
		href: 'https://apps.apple.com/us/app/microsoft-authenticator/id983156458',
		icon: mdiApple,
		platform: 'iOS',
	},
	{
		href: 'https://play.google.com/store/apps/details?id=com.azure.authenticator&hl=en_US',
		icon: mdiGooglePlay,
		platform: 'android',
	},
]

async function cancel (): PV {
	twoFAModule().set_secret(undefined)
	twoFAModule().set_setupProcessStarted(false)
	await axios_authenticatedUser.setupTwoFA_delete()
}

async function verify (): PV {
	if (!userToken.value) {
		errorMessage.value = 'code required'
		return
	} else if (!(/^[0-9]{6}$/).test(userToken.value.replace(/\s/g, ''))) {
		errorMessage.value = 'code invalid'
		return
	}
	const response = await axios_authenticatedUser.setupTwoFA_post({ token: userToken.value })
	if (response) {
		Promise.all([
			axios_authenticatedUser.setupTwoFA_delete(),
			twoFAModule().set_active(true),
			twoFAModule().set_secret(undefined),
			twoFAModule().set_setupProcessStarted(false),
		])
		snackSuccess({ message: 'two factor authentication activated' })
	}
}

watch(userToken, i => {
	if (!i) errorMessage.value = undefined
})

</script>
