/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminBackup: typeof import('./src/components/Admin/AdminBackup.vue')['default']
    AdminEmail: typeof import('./src/components/Admin/AdminEmail.vue')['default']
    AdminError: typeof import('./src/components/Admin/AdminError.vue')['default']
    AdminLimit: typeof import('./src/components/Admin/AdminLimit.vue')['default']
    AdminMemory: typeof import('./src/components/Admin/AdminMemory.vue')['default']
    AdminRegisteredUsers: typeof import('./src/components/Admin/AdminRegisteredUsers.vue')['default']
    AnalysisSection: typeof import('./src/components/Food/Analysis/AnalysisSection.vue')['default']
    AppBar: typeof import('./src/components/Nav/AppBar.vue')['default']
    ButtonIcon: typeof import('./src/components/Buttons/ButtonIcon.vue')['default']
    CategoriesTable: typeof import('./src/components/Food/Analysis/CategoriesTable.vue')['default']
    CategorySelector: typeof import('./src/components/Selectors/CategorySelector.vue')['default']
    ChangePassword: typeof import('./src/components/Settings/ChangePassword.vue')['default']
    CustomSearchSelector: typeof import('./src/components/Selectors/CustomSearchSelector.vue')['default']
    DateRow: typeof import('./src/components/Buttons/DateRow.vue')['default']
    DownloadDialog: typeof import('./src/components/Food/DownloadDialog.vue')['default']
    EmptyComponent: typeof import('./src/components/EmptyComponent.vue')['default']
    FilterButtons: typeof import('./src/components/Buttons/FilterButtons.vue')['default']
    FooterText: typeof import('./src/components/Footer/FooterText.vue')['default']
    GenericButton: typeof import('./src/components/Buttons/GenericButton.vue')['default']
    HibpMessage: typeof import('./src/components/HibpMessage.vue')['default']
    InfoBar: typeof import('./src/components/InfoBar.vue')['default']
    MealDescription: typeof import('./src/components/Food/DataTable/MealDescription.vue')['default']
    MealTable: typeof import('./src/components/Food/DataTable/MealTable.vue')['default']
    NavMenu: typeof import('./src/components/Nav/NavMenu.vue')['default']
    OfflineRow: typeof import('./src/components/OfflineRow.vue')['default']
    PasswordContainsEmail: typeof import('./src/components/PasswordContainsEmail.vue')['default']
    RefreshButton: typeof import('./src/components/Buttons/RefreshButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectorButton: typeof import('./src/components/Buttons/SelectorButton.vue')['default']
    SnackBar: typeof import('./src/components/SnackBar.vue')['default']
    TFAAlwaysRequired: typeof import('./src/components/Settings/TwoFA/TFAAlwaysRequired.vue')['default']
    TFABackup: typeof import('./src/components/Settings/TwoFA/TFABackup.vue')['default']
    TFAInactive: typeof import('./src/components/Settings/TwoFA/TFAInactive.vue')['default']
    TFAInstructions: typeof import('./src/components/Settings/TwoFA/TFAInstructions.vue')['default']
    TFAStatusRow: typeof import('./src/components/Settings/TwoFA/TFAStatusRow.vue')['default']
    TheDialog: typeof import('./src/components/TheDialog.vue')['default']
    TheFooter: typeof import('./src/components/Footer/TheFooter.vue')['default']
    TotalsTable: typeof import('./src/components/Food/Analysis/TotalsTable.vue')['default']
    TwoFactor: typeof import('./src/components/Settings/TwoFactor.vue')['default']
    TypeSelector: typeof import('./src/components/Selectors/TypeSelector.vue')['default']
    UpArrow: typeof import('./src/components/Buttons/UpArrow.vue')['default']
    UserActive: typeof import('./src/components/Admin/RegisteredUsers/UserActive.vue')['default']
    UserPassword: typeof import('./src/components/Admin/RegisteredUsers/UserPassword.vue')['default']
  }
}
