export enum ModuleName {
	Admin = 'admin',
	Browser = 'browser',
	Categories = 'categories',
	Dialog = 'dialog',
	Drawer='drawer',
	Food ='food',
	Footer = 'footer',
	Infobar = 'infobar',
	Loading = 'loading',
	Meals = 'meals',
	ResetPassword = 'resetPassword',
	Selectors = 'selectors',
	Snack = 'snackbar',
	TableData = 'tableData',
	TwoFa = 'twoFA',
	Types = 'types',
	User = 'user',
}